# Generated by Django 5.0.1 on 2025-10-14 17:22

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularRoute',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('pickup_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('pickup_address', models.TextField()),
                ('pickup_district', models.CharField(max_length=100)),
                ('destination_latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('destination_longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('destination_address', models.TextField()),
                ('destination_district', models.CharField(max_length=100)),
                ('ride_count', models.PositiveIntegerField(default=1)),
                ('average_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_duration', models.DecimalField(decimal_places=2, max_digits=6)),
                ('average_distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peak_hour', models.PositiveIntegerField()),
                ('weekly_pattern', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('first_recorded', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ride_count', '-last_updated'],
                'indexes': [models.Index(fields=['pickup_district', 'destination_district'], name='analytics_p_pickup__1da31a_idx'), models.Index(fields=['ride_count'], name='analytics_p_ride_co_5facfd_idx'), models.Index(fields=['last_updated'], name='analytics_p_last_up_5bcc89_idx')],
            },
        ),
        migrations.CreateModel(
            name='RideMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hour', models.PositiveIntegerField(blank=True, null=True)),
                ('aggregation_type', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('completed_rides', models.PositiveIntegerField(default=0)),
                ('cancelled_rides', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_ride_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_distance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('average_distance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('total_duration', models.PositiveIntegerField(default=0)),
                ('average_duration', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('active_drivers', models.PositiveIntegerField(default=0)),
                ('unique_customers', models.PositiveIntegerField(default=0)),
                ('kigali_rides', models.PositiveIntegerField(default=0)),
                ('province_breakdown', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-hour'],
                'indexes': [models.Index(fields=['date', 'aggregation_type'], name='analytics_r_date_acf0a8_idx'), models.Index(fields=['date', 'hour'], name='analytics_r_date_b10b32_idx')],
                'unique_together': {('date', 'hour', 'aggregation_type')},
            },
        ),
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('ride_summary', 'Ride Summary'), ('revenue_report', 'Revenue Report'), ('driver_performance', 'Driver Performance'), ('customer_insights', 'Customer Insights'), ('popular_routes', 'Popular Routes'), ('time_patterns', 'Time Patterns')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('data', models.JSONField()),
                ('metadata', models.JSONField(default=dict)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['report_type', 'start_date', 'end_date'], name='analytics_a_report__b5c01d_idx'), models.Index(fields=['generated_at'], name='analytics_a_generat_d331f3_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('average_ride_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('preferred_payment_method', models.CharField(blank=True, max_length=20)),
                ('preferred_ride_type', models.CharField(blank=True, max_length=20)),
                ('most_common_pickup_district', models.CharField(blank=True, max_length=100)),
                ('most_common_destination_district', models.CharField(blank=True, max_length=100)),
                ('peak_usage_hour', models.PositiveIntegerField(blank=True, null=True)),
                ('weekend_vs_weekday_ratio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('days_since_first_ride', models.PositiveIntegerField(default=0)),
                ('days_since_last_ride', models.PositiveIntegerField(default=0)),
                ('loyalty_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_rating_given', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_spent', '-total_rides'],
                'indexes': [models.Index(fields=['total_rides', 'total_spent'], name='analytics_c_total_r_b11099_idx'), models.Index(fields=['loyalty_score'], name='analytics_c_loyalty_221241_idx'), models.Index(fields=['last_updated'], name='analytics_c_last_up_2398ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverPerformanceMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_rides', models.PositiveIntegerField(default=0)),
                ('completed_rides', models.PositiveIntegerField(default=0)),
                ('cancelled_rides', models.PositiveIntegerField(default=0)),
                ('online_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('acceptance_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('commission_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_distance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('fuel_efficiency_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-gross_earnings'],
                'indexes': [models.Index(fields=['driver', 'date'], name='analytics_d_driver__a04c40_idx'), models.Index(fields=['date', 'gross_earnings'], name='analytics_d_date_1dc28d_idx'), models.Index(fields=['completion_rate'], name='analytics_d_complet_cfa51a_idx')],
                'unique_together': {('driver', 'date')},
            },
        ),
    ]
