# Generated by Django 5.0.1 on 2025-10-14 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
    ]
