# Generated by Django 5.0.1 on 2025-10-14 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('airport', 'Airport'), ('hospital', 'Hospital'), ('shopping', 'Shopping Center'), ('school', 'School/University'), ('government', 'Government Office'), ('transport', 'Transport Hub'), ('tourist', 'Tourist Attraction'), ('business', 'Business District')], max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('address', models.TextField()),
                ('province', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('booking_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'popular_destinations',
                'indexes': [models.Index(fields=['category', 'is_active'], name='popular_des_categor_a41d79_idx'), models.Index(fields=['booking_count'], name='popular_des_booking_612f12_idx')],
            },
        ),
        migrations.CreateModel(
            name='DriverLocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('speed', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('heading', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('is_online', models.BooleanField()),
                ('is_on_ride', models.BooleanField(default=False)),
                ('ride_id', models.UUIDField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'driver_location_history',
                'indexes': [models.Index(fields=['driver', 'timestamp'], name='driver_loca_driver__f8e3a5_idx'), models.Index(fields=['timestamp'], name='driver_loca_timesta_81fc58_idx')],
            },
        ),
        migrations.CreateModel(
            name='RwandaLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('province', 'Province'), ('district', 'District'), ('sector', 'Sector'), ('cell', 'Cell'), ('village', 'Village'), ('landmark', 'Landmark')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('administrative_code', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='locations.rwandalocation')),
            ],
            options={
                'db_table': 'rwanda_locations',
                'indexes': [models.Index(fields=['location_type', 'parent'], name='rwanda_loca_locatio_7f9d14_idx'), models.Index(fields=['name'], name='rwanda_loca_name_7e2117_idx')],
            },
        ),
    ]
