# Generated by Django 5.0.1 on 2025-10-17 13:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_ridelocation_ride'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('cell', models.CharField(blank=True, max_length=100)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'locations',
                'indexes': [models.Index(fields=['district', 'is_popular'], name='locations_distric_8e8547_idx'), models.Index(fields=['is_popular', 'is_active'], name='locations_is_popu_d2af14_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('speed', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('heading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('accuracy', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to='bookings.ride')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'location_updates',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='location_up_user_id_a71c7d_idx'), models.Index(fields=['ride', 'timestamp'], name='location_up_ride_id_1da60c_idx'), models.Index(fields=['timestamp'], name='location_up_timesta_371544_idx')],
            },
        ),
    ]
