# Generated by Django 5.0.1 on 2025-10-17 13:21

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smsprovider',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_e285de_idx',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='subject',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='enable_email',
            new_name='email_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='promotional_messages',
            new_name='marketing_email',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='enable_in_app',
            new_name='payment_updates',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='enable_push',
            new_name='push_enabled',
        ),
        migrations.RenameField(
            model_name='notificationpreference',
            old_name='enable_sms',
            new_name='sms_enabled',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='body_template',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='notificationtemplate',
            old_name='subject_template',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='smsprovider',
            old_name='api_url',
            new_name='api_endpoint',
        ),
        migrations.RenameField(
            model_name='smsprovider',
            old_name='daily_limit',
            new_name='rate_limit',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='context_data',
        ),
        migrations.RemoveField(
            model_name='notificationpreference',
            name='payment_notifications',
        ),
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App')], default='sms', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('rw', 'Kinyarwanda')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='marketing_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='promotional_offers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('rw', 'Kinyarwanda')], default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='password',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='priority',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='provider_type',
            field=models.CharField(choices=[('mtn', 'MTN Rwanda'), ('airtel', 'Airtel Rwanda'), ('tigo', 'Tigo Rwanda')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smsprovider',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('push', 'Push Notification'), ('in_app', 'In-App Notification'), ('ride_update', 'Ride Update'), ('general', 'General'), ('account', 'Account')], max_length=20),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='cost_per_sms',
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='smsprovider',
            name='sender_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'status'], name='notificatio_user_id_7088ed_idx'),
        ),
    ]
